version: "3.9"

services:
  mysql:
    image: swr.cn-north-4.myhuaweicloud.com/oomall-javaee/mysql:latest
    networks:
      - javaee-proxy
    ports:
      - target: 3306 # Container port (Traefik web entry point)
        published: 3306 # Host port exposed on the nodes
        protocol: tcp
    volumes:
      - /root/mysql/sql:/sql:ro
      - /root/mysql/conf.d:/etc/mysql/conf.d:ro
      - /root/mysql/log:/var/log/mysql
      - /root/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Ooad_2_8
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.mysql==yes

  aftersale:
    image: swr.cn-north-4.myhuaweicloud.com/oomall-javaeeh/aftersale:0.0.1-SNAPSHOT
    networks:
      - javaee-proxy
    ports:
      - target: 8080 # Container port (Traefik web entry point)
        published: 8080 # Host port exposed on the nodes
        protocol: tcp
    volumes:
      - /root/logs_aftersale:/app/logs
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.aftersale==yes
    command:
      - "--spring.datasource.url=jdbc:mysql://mysql:3306/oomall_demo?serverTimezone=Asia/Shanghai"
      - "--spring.datasource.username=demouser"
      - "--spring.datasource.password=Ooad_2_8"
      - "--server.tomcat.threads.max=8000"
      - "--spring.datasource.druid.max-active=500"
      - "--spring.datasource.druid.min-idle=50"
      - "--spring.datasource.druid.initial-size=50"
      - "--spring.datasource.druid.stat-view-servlet.login-password=123456"
      - "--service.order.base-url=http://service:8081"

  service:
    image: swr.cn-north-4.myhuaweicloud.com/oomall-javaeeh/service:0.0.1-SNAPSHOT
    networks:
      - javaee-proxy
    ports:
      - target: 8081 # Container port (Traefik web entry point)
        published: 8081 # Host port exposed on the nodes
        protocol: tcp
    volumes:
      - /root/logs_service:/app/logs
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.service==yes
    command:
      - "--spring.datasource.url=jdbc:mysql://mysql:3306/oomall_demo?serverTimezone=Asia/Shanghai"
      - "--spring.datasource.username=demouser"
      - "--spring.datasource.password=Ooad_2_8"
      - "--server.tomcat.threads.max=8000"
      - "--spring.datasource.druid.max-active=500"
      - "--spring.datasource.druid.min-idle=50"
      - "--spring.datasource.druid.initial-size=50"
      - "--spring.datasource.druid.stat-view-servlet.login-password=123456"


networks:
  javaee-proxy:
    driver: overlay
    attachable: true
    external: true