###
PUT http://localhost:8080/shops/1001/aftersales/2001/confirm
Content-Type: application/json

{
  "confirm": true,
  "conclusion": "审核通过",
  "type": 1
}

> {%
    client.test("审核通过-状态码200", function() {
        client.assert(response.status === 200, "预期200，实际：" + response.status);
    });

    client.test("审核通过-返回结果正确", function() {
        const res = JSON.parse(response.body);
        client.assert(res.code === 200, "返回码错误：" + res.code);
        client.assert(res.msg === "审核成功", "提示语错误：" + res.msg);
    });
%}

###
PUT http://localhost:8080/shops/1001/aftersales/2002/confirm
Content-Type: application/json

{
  "confirm": false,
  "conclusion": "凭证不足，驳回",
  "type": 1
}